version: "3.8"

networks:
  traefik-public:
    external: true

services:
  bot:
    image: "henriquegemignani/discord-shared-messages:edge"

    environment:
      - "SANIC_DISCORD_TOKEN=${DISCORD_TOKEN}"
      - "SANIC_OAUTH_CLIENT_ID=${DISCORD_OAUTH_CLIENT_ID}"
      - "SANIC_OAUTH_CLIENT_SECRET=${DISCORD_OAUTH_CLIENT_SECRET}"
      - "SANIC_OAUTH_REDIRECT_URI=https://${DOMAIN}/${PATH_PREFIX}/oauth"
      - "SANIC_PROXIES_COUNT=1"
      - "SANIC_SERVER_NAME=https://${DOMAIN}/${PATH_PREFIX}"

    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - "traefik.http.routers.${PATH_PREFIX}.rule=Host(`${DOMAIN}`) && PathPrefix(`/${PATH_PREFIX}`)"
        - "traefik.http.routers.${PATH_PREFIX}.entrypoints=websecure"
        - "traefik.http.routers.${PATH_PREFIX}.tls.certresolver=le"
        - "traefik.http.routers.${PATH_PREFIX}.middlewares=${PATH_PREFIX}_stripprefix"
        - "traefik.http.middlewares.${PATH_PREFIX}_stripprefix.stripprefix.prefixes=/${PATH_PREFIX}"
        - "traefik.http.services.${PATH_PREFIX}.loadbalancer.server.port=8000"

    networks:
      - traefik-public
